## Переменные и типы данных

In [3]:
# Type check
x = 5
type(x)

int

Other variable types

int, or integer: a number without a fractional paes:

float, or floating point: a number that has both an integer and fractional part, separated by a pfloat.
str, or string: a type to represent text. You can use single or double quotes to build a string.
bool, or boolean: a type to represent logical values. It can only be True or False (the capitalization is important!).

In [5]:
# Type change (int(), float() and bool())
x = 5
type(str(x))

str

## Списки, индексы и слайсы

Есть еще переменная list с списками [1, 2, 3]

In [6]:
# Через индексы можно ссылаться на конкретное значение в списке (нумерация начинается с нулевого индекса 0)
x = [3, 6, 7, 76, 45, 5]
print(x[2]) # ссылаемся на 2 значение, но по счету оно 3

7


In [7]:
# Отрицательный индекс начинает счет с конца
print(x[-2]) # здесь сразу счет, без 0

45


In [8]:
# Слайсер позволяет создавать списки из списков. my_list[start:end] The start index will be included, while the end index is not.
print(x[3:5]) # окончание диапазона не входит в счет (5 значение не отобразилось)

[76, 45]


In [9]:
# Если не указывать начало или конец, то будет выведено все до или после
print(x[:5])

[3, 6, 7, 76, 45]


In [10]:
# С этими подмножествами (subset, set - множество) можно производить операции
print(x[2] + x[-2])

52


The ; sign is used to place commands on the same line. The following two code chunks are equivalent:

Same line
command1; command2

Separate lines
command1
command2

In [13]:
# Можно удалять значения через del
y = ["a", "b", "c", "d"]
del(y[1])
print(y)

['a', 'c', 'd']


In [14]:
# Можно добавлять через +
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
print(y)

['a', 'b', 'c', 'd', 'e', 'f']


In [15]:
# Когда мы копируем переменную через равенство (х=у), то мы копируем путь к значениям. Списки хранят не сами значения, а ссылки на них. 
# При изменении y в таком случае изменится и х
x = ["a", "b", "c"]
y = x
y[1] = "z"
print(x); print(y)

['a', 'z', 'c']
['a', 'z', 'c']


In [16]:
# Нужно копировать списки через list или индексы
x = ["a", "b", "c"]
y = list(x)
y = x[:]
y[1] = "z"
print(x); print(y)

['a', 'b', 'c']
['a', 'z', 'c']


## Функции

В функцию подаются аргументы
print(), int(), str(), max(), round(5.676, 2), len() - длина значения, pow(5, 2) - возведение 5 в степень 2

In [4]:
# str.lower() — конвертирует все символы в верхнем регистре в нижний регистр. str.upper() - аналогичная функция с верхним рег.
s1 = "Hello How are you"
print(s1.lower())

hello how are you


In [5]:
# string.split(separator*, maxsplit*) - разделяет строку. seperator - если хотим разделить по символу (",") maxsplit - количество делений
print(s1.split())

['Hello', 'How', 'are', 'you']


In [20]:
# sorted(iterable,key=None,reverse=False) - возвращает новый отсортированный список итерируемого объекта 
# iterable: строка, список, кортеж, множество, словарь 
# key (необязательный параметр): если указать ключ, то сортировка будет выполнена по функции этого ключа. 
#reverse (необязательный параметр): по умолчанию сортировка выполняется по возрастанию. True - по убыванию
print(sorted(s1.split(), key=str.lower, reverse=True))

['you', 'How', 'Hello', 'are']


## Метод

Метод — это такая функция, которую можно использовать для определенного типа данных. 
Существуют строковые методы, методы для работы с целыми числами, методы списков, словарей и т.д.

Иногда вы можете задаться вопросом, существует ли какой-то метод. В Python можно посмотреть весь список строковых методов, используя функцию dir() со строкой в ​​качестве аргумента

In [7]:
# То, что мы подаем(переменная) - это называется Объект. у объекта есть тип и значение
dir(s1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

Вызвать метод index в fam, и на выходе было 4
append(), that adds an element to the list it is called on,
remove(), that removes the first element of a list that matches the input, and
reverse(), that reverses the order of the elements in the list it is called on.

## Packages (библиотеки, пакеты)

there's NumPy to efficiently work with arrays, Matplotlib for data visualization, and scikit-learn for machine learning

pip - система обслуживания пакетов (библиотек) для python. Для уставновки пакетов лучше писать pip3 install ... чтобы ссылаться точно на 3 версию питона

In [25]:
# Импортируем всю библиотеку, тогда указываем имя библиотеки при вызове функции (можно дать алиас через as)
import math
print(math.pi)

3.141592653589793


In [26]:
# Можно импортировать оттдельную функцию, тогда при ее вызове не указываем библиотеку
from math import pi
print(pi)

3.141592653589793


#### NumPy (Numeric Python)

Массивы(arrays) в NumPy - альтернатива списков (lists) в Python. Над массивами можно производить вычисления. В массиве все значения должны быть одного типа, или функция array преобразует все в текст. Array - такой же тип, как string, boolean и т.д. и у него также есть свои методы.

In [30]:
# Преобразуем список в массив
import numpy as np
x = [5, 7, 25, 13, 75, 34]
ar_x = np.array(x)
print(ar_x)

[ 5  7 25 13 75 34]


In [31]:
# В массивах также можно использовать индексы
print(ar_x[4])

75


In [32]:
# Выведем проверку 
print(ar_x > 20)

[False False  True False  True  True]


In [34]:
# Отфильтруем только значения > 20
print(ar_x[ar_x > 20])

[25 75 34]


In [36]:
# Можно задать значение в квадратных скобках переменной
ar_x2 = ar_x > 20
print(ar_x[ar_x2])

[25 75 34]


Приведение типа (type coercion) - преобразование одного типа в другой, например, строку в число, число в строку, число в булеву переменную, строку в дробь и так далее. 
Numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. 

In [38]:
# The typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

Subsetting(подстановка) - using the square bracket notation on lists or arrays

#### 2D NumPy Array

numpy.ndarray - If you ask for the type of these arrays, Python tells you that they are numpy-dot-ndarray. numpy dot tells you it's a type that was defined in the numpy package. ndarray stands for n-dimensional array. 

In [43]:
# 2d списки при отображении выводятся табличкой, каждому элементу первого множества соответствуем элемент второго
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)
print(np_2d.shape) # выводит строки, столбцы

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)


In [47]:
# Предположим есть множество
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
# Оно представлено в табличном виде, есть строки рост и вес и столбцы игроков
# Можно делать любые срезы, например
# вывести рост и вес 1 игрока
print(np_2d[:, 0]) # [строки от:до, столбцы от:до]

[ 1.73 65.4 ]


In [49]:
# Списки Python не могут представлять значения в табл виде и нужно все элементы указывать вручную
x = [["a", "b"], 
     ["c", "d"]]
[x[0][0], x[1][0]]

['a', 'c']

#### NumPy: Basic Statistics

Функции(методы), для статистической обработки
<br>
<br>
mean() - среднее
<br>
median() - медиана (серединное значение выборки, отсортированной по порядку)
<br>
corrcoef(var1, var2) - рассчитать корреляцию между двумя массивами
<br>
std() - cтандартное отклонение – это мера, на которую элементы набора отклоняются или расходятся от среднего значения5

In [52]:
# Функция Numpy random normal() генерирует массив заданных фигур и заполняет его случайными значениями, которые на самом деле являются 
# частью нормального(гауссовского)распределения.
# Arguments for np.random.normal()
# distribution mean (loc) - Loc означает среднее значение случайных величин, выбранных из функции
# distribution standard deviation (scale) - шкала означает стандартное отклонение значений, выбранных из функции
# number of samples (size) - размер означает количество значений в массиве.
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight)) # объединяем два столбца
print(np_city)

[[ 2.   51.48]
 [ 1.62 58.09]
 [ 1.75 58.35]
 ...
 [ 1.51 76.15]
 [ 1.98 71.15]
 [ 1.78 67.69]]


Двойное равно == в большинстве языках программирования, означает операцию равенство, просто = означает присвоение значения переменной. 
<br>
= и == это два разных операций, первое приваивает значение с правой стороны в левую например a = 5 означает что в переменную a было присвоено 
<br>
значение 5, а запись a == 5 означает операцию сравнения, возвращая результат в виде логического значения true или false